// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// A rectangle in output pixels (origin top-left).
class NativeRect {
  NativeRect({
    required this.left,
    required this.top,
    required this.width,
    required this.height,
  });

  double left;

  double top;

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[left, top, width, height];
  }

  Object encode() {
    return _toList();
  }

  static NativeRect decode(Object result) {
    result as List<Object?>;
    return NativeRect(
      left: result[0]! as double,
      top: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeRect || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(left, other.left) &&
        _deepEquals(top, other.top) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeRect(left: $left, top: $top, width: $width, height: $height)';
  }
}

/// An extra audio track mixed into the output.
class NativeAudioTrack {
  NativeAudioTrack({
    required this.path,
    required this.startMs,
    required this.volume,
  });

  /// Local audio file (M4A/AAC, MP3, WAV).
  String path;

  /// Offset into the audio file where playback starts.
  int startMs;

  /// 0–1.
  double volume;

  List<Object?> _toList() {
    return <Object?>[path, startMs, volume];
  }

  Object encode() {
    return _toList();
  }

  static NativeAudioTrack decode(Object result) {
    result as List<Object?>;
    return NativeAudioTrack(
      path: result[0]! as String,
      startMs: result[1]! as int,
      volume: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAudioTrack || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) &&
        _deepEquals(startMs, other.startMs) &&
        _deepEquals(volume, other.volume);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAudioTrack(path: $path, startMs: $startMs, volume: $volume)';
  }
}

/// Common output settings.
class NativeOutput {
  NativeOutput({
    required this.path,
    required this.width,
    required this.height,
    required this.frameRate,
    required this.videoBitrate,
  });

  /// Destination .mp4 path; overwritten if it exists.
  String path;

  int width;

  int height;

  int frameRate;

  /// H.264 target bitrate, bits per second.
  int videoBitrate;

  List<Object?> _toList() {
    return <Object?>[path, width, height, frameRate, videoBitrate];
  }

  Object encode() {
    return _toList();
  }

  static NativeOutput decode(Object result) {
    result as List<Object?>;
    return NativeOutput(
      path: result[0]! as String,
      width: result[1]! as int,
      height: result[2]! as int,
      frameRate: result[3]! as int,
      videoBitrate: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeOutput || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(frameRate, other.frameRate) &&
        _deepEquals(videoBitrate, other.videoBitrate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeOutput(path: $path, width: $width, height: $height, frameRate: $frameRate, videoBitrate: $videoBitrate)';
  }
}

/// Export of a source video onto the story canvas.
///
/// Frame composition, bottom to top:
///   1. transparent/black canvas of output size
///   2. the source video frame, rotated per its metadata, mirrored when
///      [mirror], colour-transformed by [colorMatrix], drawn scaled into
///      [videoRect] (may extend past the canvas; clipped)
///   3. [overlayPngPath], a full-canvas RGBA PNG drawn at (0,0) at output
///      size. It already contains the background with a transparent hole
///      where the video shows, plus drawings and overlays.
/// Audio: the source audio in [trimStartMs, trimEndMs) at [originalVolume]
/// (omitted when 0 or absent), mixed with [music] trimmed to the output
/// length. Output is AAC 44.1 kHz stereo; no audio track when both are
/// absent.
class VideoExportRequest {
  VideoExportRequest({
    required this.jobId,
    required this.sourcePath,
    required this.trimStartMs,
    required this.trimEndMs,
    required this.videoRect,
    required this.mirror,
    this.colorMatrix,
    this.overlayPngPath,
    required this.originalVolume,
    this.music,
    required this.output,
  });

  String jobId;

  String sourcePath;

  int trimStartMs;

  int trimEndMs;

  NativeRect videoRect;

  bool mirror;

  /// 20 values, row-major 4×5, offsets in 0–255 (Flutter ColorFilter.matrix
  /// semantics). `null` = identity.
  List<double>? colorMatrix;

  String? overlayPngPath;

  double originalVolume;

  NativeAudioTrack? music;

  NativeOutput output;

  List<Object?> _toList() {
    return <Object?>[
      jobId,
      sourcePath,
      trimStartMs,
      trimEndMs,
      videoRect,
      mirror,
      colorMatrix,
      overlayPngPath,
      originalVolume,
      music,
      output,
    ];
  }

  Object encode() {
    return _toList();
  }

  static VideoExportRequest decode(Object result) {
    result as List<Object?>;
    return VideoExportRequest(
      jobId: result[0]! as String,
      sourcePath: result[1]! as String,
      trimStartMs: result[2]! as int,
      trimEndMs: result[3]! as int,
      videoRect: result[4]! as NativeRect,
      mirror: result[5]! as bool,
      colorMatrix: (result[6] as List<Object?>?)?.cast<double>(),
      overlayPngPath: result[7] as String?,
      originalVolume: result[8]! as double,
      music: result[9] as NativeAudioTrack?,
      output: result[10]! as NativeOutput,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoExportRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(jobId, other.jobId) &&
        _deepEquals(sourcePath, other.sourcePath) &&
        _deepEquals(trimStartMs, other.trimStartMs) &&
        _deepEquals(trimEndMs, other.trimEndMs) &&
        _deepEquals(videoRect, other.videoRect) &&
        _deepEquals(mirror, other.mirror) &&
        _deepEquals(colorMatrix, other.colorMatrix) &&
        _deepEquals(overlayPngPath, other.overlayPngPath) &&
        _deepEquals(originalVolume, other.originalVolume) &&
        _deepEquals(music, other.music) &&
        _deepEquals(output, other.output);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoExportRequest(jobId: $jobId, sourcePath: $sourcePath, trimStartMs: $trimStartMs, trimEndMs: $trimEndMs, videoRect: $videoRect, mirror: $mirror, colorMatrix: $colorMatrix, overlayPngPath: $overlayPngPath, originalVolume: $originalVolume, music: $music, output: $output)';
  }
}

/// A video made from one still frame (photo story with music).
class StillVideoExportRequest {
  StillVideoExportRequest({
    required this.jobId,
    required this.framePath,
    required this.durationMs,
    this.music,
    required this.output,
  });

  String jobId;

  /// Fully composed frame at output size (PNG or JPEG).
  String framePath;

  int durationMs;

  NativeAudioTrack? music;

  NativeOutput output;

  List<Object?> _toList() {
    return <Object?>[jobId, framePath, durationMs, music, output];
  }

  Object encode() {
    return _toList();
  }

  static StillVideoExportRequest decode(Object result) {
    result as List<Object?>;
    return StillVideoExportRequest(
      jobId: result[0]! as String,
      framePath: result[1]! as String,
      durationMs: result[2]! as int,
      music: result[3] as NativeAudioTrack?,
      output: result[4]! as NativeOutput,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StillVideoExportRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(jobId, other.jobId) &&
        _deepEquals(framePath, other.framePath) &&
        _deepEquals(durationMs, other.durationMs) &&
        _deepEquals(music, other.music) &&
        _deepEquals(output, other.output);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StillVideoExportRequest(jobId: $jobId, framePath: $framePath, durationMs: $durationMs, music: $music, output: $output)';
  }
}

/// JPEG encoding of raw pixels.
class JpegEncodeRequest {
  JpegEncodeRequest({
    required this.rgba,
    required this.width,
    required this.height,
    required this.quality,
    required this.outputPath,
  });

  /// Straight (non-premultiplied) RGBA8888, row-major, width*height*4 bytes.
  Uint8List rgba;

  int width;

  int height;

  /// 1–100.
  int quality;

  String outputPath;

  List<Object?> _toList() {
    return <Object?>[rgba, width, height, quality, outputPath];
  }

  Object encode() {
    return _toList();
  }

  static JpegEncodeRequest decode(Object result) {
    result as List<Object?>;
    return JpegEncodeRequest(
      rgba: result[0]! as Uint8List,
      width: result[1]! as int,
      height: result[2]! as int,
      quality: result[3]! as int,
      outputPath: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! JpegEncodeRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(rgba, other.rgba) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(quality, other.quality) &&
        _deepEquals(outputPath, other.outputPath);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'JpegEncodeRequest(rgba: $rgba, width: $width, height: $height, quality: $quality, outputPath: $outputPath)';
  }
}

class NativeExportResult {
  NativeExportResult({
    required this.path,
    required this.width,
    required this.height,
    required this.fileSizeBytes,
    this.durationMs,
  });

  String path;

  int width;

  int height;

  int fileSizeBytes;

  int? durationMs;

  List<Object?> _toList() {
    return <Object?>[path, width, height, fileSizeBytes, durationMs];
  }

  Object encode() {
    return _toList();
  }

  static NativeExportResult decode(Object result) {
    result as List<Object?>;
    return NativeExportResult(
      path: result[0]! as String,
      width: result[1]! as int,
      height: result[2]! as int,
      fileSizeBytes: result[3]! as int,
      durationMs: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeExportResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(fileSizeBytes, other.fileSizeBytes) &&
        _deepEquals(durationMs, other.durationMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeExportResult(path: $path, width: $width, height: $height, fileSizeBytes: $fileSizeBytes, durationMs: $durationMs)';
  }
}

class NativeMediaProbe {
  NativeMediaProbe({
    required this.width,
    required this.height,
    required this.fileSizeBytes,
    required this.rotationDegrees,
    required this.hasVideo,
    required this.hasAudio,
    this.durationMs,
    this.videoCodec,
    this.audioCodec,
    this.frameRate,
  });

  /// Display size (rotation / EXIF orientation applied).
  int width;

  int height;

  int fileSizeBytes;

  int rotationDegrees;

  bool hasVideo;

  bool hasAudio;

  int? durationMs;

  String? videoCodec;

  String? audioCodec;

  double? frameRate;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
      fileSizeBytes,
      rotationDegrees,
      hasVideo,
      hasAudio,
      durationMs,
      videoCodec,
      audioCodec,
      frameRate,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeMediaProbe decode(Object result) {
    result as List<Object?>;
    return NativeMediaProbe(
      width: result[0]! as int,
      height: result[1]! as int,
      fileSizeBytes: result[2]! as int,
      rotationDegrees: result[3]! as int,
      hasVideo: result[4]! as bool,
      hasAudio: result[5]! as bool,
      durationMs: result[6] as int?,
      videoCodec: result[7] as String?,
      audioCodec: result[8] as String?,
      frameRate: result[9] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeMediaProbe || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(fileSizeBytes, other.fileSizeBytes) &&
        _deepEquals(rotationDegrees, other.rotationDegrees) &&
        _deepEquals(hasVideo, other.hasVideo) &&
        _deepEquals(hasAudio, other.hasAudio) &&
        _deepEquals(durationMs, other.durationMs) &&
        _deepEquals(videoCodec, other.videoCodec) &&
        _deepEquals(audioCodec, other.audioCodec) &&
        _deepEquals(frameRate, other.frameRate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeMediaProbe(width: $width, height: $height, fileSizeBytes: $fileSizeBytes, rotationDegrees: $rotationDegrees, hasVideo: $hasVideo, hasAudio: $hasAudio, durationMs: $durationMs, videoCodec: $videoCodec, audioCodec: $audioCodec, frameRate: $frameRate)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeRect) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is NativeAudioTrack) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is NativeOutput) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is VideoExportRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is StillVideoExportRequest) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is JpegEncodeRequest) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is NativeExportResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is NativeMediaProbe) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeRect.decode(readValue(buffer)!);
      case 130:
        return NativeAudioTrack.decode(readValue(buffer)!);
      case 131:
        return NativeOutput.decode(readValue(buffer)!);
      case 132:
        return VideoExportRequest.decode(readValue(buffer)!);
      case 133:
        return StillVideoExportRequest.decode(readValue(buffer)!);
      case 134:
        return JpegEncodeRequest.decode(readValue(buffer)!);
      case 135:
        return NativeExportResult.decode(readValue(buffer)!);
      case 136:
        return NativeMediaProbe.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class StoryNativeApi {
  /// Constructor for [StoryNativeApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  StoryNativeApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeExportResult> exportVideo(VideoExportRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.story_creator_kit.StoryNativeApi.exportVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeExportResult;
  }

  Future<NativeExportResult> exportStillVideo(
    StillVideoExportRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.story_creator_kit.StoryNativeApi.exportStillVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeExportResult;
  }

  Future<NativeExportResult> encodeJpeg(JpegEncodeRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.story_creator_kit.StoryNativeApi.encodeJpeg$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeExportResult;
  }

  /// Cancels a running export; its call fails with code 'cancelled' and the
  /// partial output is deleted. No-op for unknown ids.
  Future<void> cancelExport(String jobId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.story_creator_kit.StoryNativeApi.cancelExport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[jobId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Images (JPEG, PNG, HEIC, WebP) and videos.
  Future<NativeMediaProbe> probe(String path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.story_creator_kit.StoryNativeApi.probe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeMediaProbe;
  }

  /// Peak levels 0–1 in [buckets] even slices of the whole file's audio.
  Future<List<double>> waveform(String path, int buckets) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.story_creator_kit.StoryNativeApi.waveform$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path, buckets],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<double>();
  }

  /// JPEG frames at [timesMs], at most [maxWidth] wide, written into
  /// [outputDirectory]; returns paths in the same order.
  Future<List<String>> thumbnails(
    String path,
    List<int> timesMs,
    int maxWidth,
    String outputDirectory,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.story_creator_kit.StoryNativeApi.thumbnails$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path, timesMs, maxWidth, outputDirectory],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }
}

abstract class StoryNativeEvents {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Progress 0–1 of a running export.
  void onExportProgress(String jobId, double progress);

  static void setUp(
    StoryNativeEvents? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.story_creator_kit.StoryNativeEvents.onExportProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_jobId = args[0]! as String;
          final double arg_progress = args[1]! as double;
          try {
            api.onExportProgress(arg_jobId, arg_progress);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
