// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum StoryNativeApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// A rectangle in output pixels (origin top-left).
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeRect: Hashable, CustomStringConvertible {
  var left: Double
  var top: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeRect? {
    let left = pigeonVar_list[0] as! Double
    let top = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return NativeRect(
      left: left,
      top: top,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      left,
      top,
      width,
      height,
    ]
  }
  static func == (lhs: NativeRect, rhs: NativeRect) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return StoryNativeApiPigeonInternal.deepEquals(lhs.left, rhs.left) && StoryNativeApiPigeonInternal.deepEquals(lhs.top, rhs.top) && StoryNativeApiPigeonInternal.deepEquals(lhs.width, rhs.width) && StoryNativeApiPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeRect")
    StoryNativeApiPigeonInternal.deepHash(value: left, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: top, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "NativeRect(left: \(String(describing: left)), top: \(String(describing: top)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// An extra audio track mixed into the output.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeAudioTrack: Hashable, CustomStringConvertible {
  /// Local audio file (M4A/AAC, MP3, WAV).
  var path: String
  /// Offset into the audio file where playback starts.
  var startMs: Int64
  /// 0–1.
  var volume: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAudioTrack? {
    let path = pigeonVar_list[0] as! String
    let startMs = pigeonVar_list[1] as! Int64
    let volume = pigeonVar_list[2] as! Double

    return NativeAudioTrack(
      path: path,
      startMs: startMs,
      volume: volume
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      startMs,
      volume,
    ]
  }
  static func == (lhs: NativeAudioTrack, rhs: NativeAudioTrack) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return StoryNativeApiPigeonInternal.deepEquals(lhs.path, rhs.path) && StoryNativeApiPigeonInternal.deepEquals(lhs.startMs, rhs.startMs) && StoryNativeApiPigeonInternal.deepEquals(lhs.volume, rhs.volume)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAudioTrack")
    StoryNativeApiPigeonInternal.deepHash(value: path, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: startMs, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: volume, hasher: &hasher)
  }

  public var description: String {
    return "NativeAudioTrack(path: \(String(describing: path)), startMs: \(String(describing: startMs)), volume: \(String(describing: volume)))"
  }
}

/// Common output settings.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeOutput: Hashable, CustomStringConvertible {
  /// Destination .mp4 path; overwritten if it exists.
  var path: String
  var width: Int64
  var height: Int64
  var frameRate: Int64
  /// H.264 target bitrate, bits per second.
  var videoBitrate: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeOutput? {
    let path = pigeonVar_list[0] as! String
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let frameRate = pigeonVar_list[3] as! Int64
    let videoBitrate = pigeonVar_list[4] as! Int64

    return NativeOutput(
      path: path,
      width: width,
      height: height,
      frameRate: frameRate,
      videoBitrate: videoBitrate
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      width,
      height,
      frameRate,
      videoBitrate,
    ]
  }
  static func == (lhs: NativeOutput, rhs: NativeOutput) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return StoryNativeApiPigeonInternal.deepEquals(lhs.path, rhs.path) && StoryNativeApiPigeonInternal.deepEquals(lhs.width, rhs.width) && StoryNativeApiPigeonInternal.deepEquals(lhs.height, rhs.height) && StoryNativeApiPigeonInternal.deepEquals(lhs.frameRate, rhs.frameRate) && StoryNativeApiPigeonInternal.deepEquals(lhs.videoBitrate, rhs.videoBitrate)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeOutput")
    StoryNativeApiPigeonInternal.deepHash(value: path, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: frameRate, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: videoBitrate, hasher: &hasher)
  }

  public var description: String {
    return "NativeOutput(path: \(String(describing: path)), width: \(String(describing: width)), height: \(String(describing: height)), frameRate: \(String(describing: frameRate)), videoBitrate: \(String(describing: videoBitrate)))"
  }
}

/// Export of a source video onto the story canvas.
///
/// Frame composition, bottom to top:
///   1. transparent/black canvas of output size
///   2. the source video frame, rotated per its metadata, mirrored when
///      [mirror], colour-transformed by [colorMatrix], drawn scaled into
///      [videoRect] (may extend past the canvas; clipped)
///   3. [overlayPngPath], a full-canvas RGBA PNG drawn at (0,0) at output
///      size. It already contains the background with a transparent hole
///      where the video shows, plus drawings and overlays.
/// Audio: the source audio in [trimStartMs, trimEndMs) at [originalVolume]
/// (omitted when 0 or absent), mixed with [music] trimmed to the output
/// length. Output is AAC 44.1 kHz stereo; no audio track when both are
/// absent.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VideoExportRequest: Hashable, CustomStringConvertible {
  var jobId: String
  var sourcePath: String
  var trimStartMs: Int64
  var trimEndMs: Int64
  var videoRect: NativeRect
  var mirror: Bool
  /// 20 values, row-major 4×5, offsets in 0–255 (Flutter ColorFilter.matrix
  /// semantics). `null` = identity.
  var colorMatrix: [Double]? = nil
  var overlayPngPath: String? = nil
  var originalVolume: Double
  var music: NativeAudioTrack? = nil
  var output: NativeOutput


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoExportRequest? {
    let jobId = pigeonVar_list[0] as! String
    let sourcePath = pigeonVar_list[1] as! String
    let trimStartMs = pigeonVar_list[2] as! Int64
    let trimEndMs = pigeonVar_list[3] as! Int64
    let videoRect = pigeonVar_list[4] as! NativeRect
    let mirror = pigeonVar_list[5] as! Bool
    let colorMatrix: [Double]? = nilOrValue(pigeonVar_list[6])
    let overlayPngPath: String? = nilOrValue(pigeonVar_list[7])
    let originalVolume = pigeonVar_list[8] as! Double
    let music: NativeAudioTrack? = nilOrValue(pigeonVar_list[9])
    let output = pigeonVar_list[10] as! NativeOutput

    return VideoExportRequest(
      jobId: jobId,
      sourcePath: sourcePath,
      trimStartMs: trimStartMs,
      trimEndMs: trimEndMs,
      videoRect: videoRect,
      mirror: mirror,
      colorMatrix: colorMatrix,
      overlayPngPath: overlayPngPath,
      originalVolume: originalVolume,
      music: music,
      output: output
    )
  }
  func toList() -> [Any?] {
    return [
      jobId,
      sourcePath,
      trimStartMs,
      trimEndMs,
      videoRect,
      mirror,
      colorMatrix,
      overlayPngPath,
      originalVolume,
      music,
      output,
    ]
  }
  static func == (lhs: VideoExportRequest, rhs: VideoExportRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return StoryNativeApiPigeonInternal.deepEquals(lhs.jobId, rhs.jobId) && StoryNativeApiPigeonInternal.deepEquals(lhs.sourcePath, rhs.sourcePath) && StoryNativeApiPigeonInternal.deepEquals(lhs.trimStartMs, rhs.trimStartMs) && StoryNativeApiPigeonInternal.deepEquals(lhs.trimEndMs, rhs.trimEndMs) && StoryNativeApiPigeonInternal.deepEquals(lhs.videoRect, rhs.videoRect) && StoryNativeApiPigeonInternal.deepEquals(lhs.mirror, rhs.mirror) && StoryNativeApiPigeonInternal.deepEquals(lhs.colorMatrix, rhs.colorMatrix) && StoryNativeApiPigeonInternal.deepEquals(lhs.overlayPngPath, rhs.overlayPngPath) && StoryNativeApiPigeonInternal.deepEquals(lhs.originalVolume, rhs.originalVolume) && StoryNativeApiPigeonInternal.deepEquals(lhs.music, rhs.music) && StoryNativeApiPigeonInternal.deepEquals(lhs.output, rhs.output)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoExportRequest")
    StoryNativeApiPigeonInternal.deepHash(value: jobId, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: sourcePath, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: trimStartMs, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: trimEndMs, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: videoRect, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: mirror, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: colorMatrix, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: overlayPngPath, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: originalVolume, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: music, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: output, hasher: &hasher)
  }

  public var description: String {
    return "VideoExportRequest(jobId: \(String(describing: jobId)), sourcePath: \(String(describing: sourcePath)), trimStartMs: \(String(describing: trimStartMs)), trimEndMs: \(String(describing: trimEndMs)), videoRect: \(String(describing: videoRect)), mirror: \(String(describing: mirror)), colorMatrix: \(String(describing: colorMatrix)), overlayPngPath: \(String(describing: overlayPngPath)), originalVolume: \(String(describing: originalVolume)), music: \(String(describing: music)), output: \(String(describing: output)))"
  }
}

/// A video made from one still frame (photo story with music).
///
/// Generated class from Pigeon that represents data sent in messages.
struct StillVideoExportRequest: Hashable, CustomStringConvertible {
  var jobId: String
  /// Fully composed frame at output size (PNG or JPEG).
  var framePath: String
  var durationMs: Int64
  var music: NativeAudioTrack? = nil
  var output: NativeOutput


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StillVideoExportRequest? {
    let jobId = pigeonVar_list[0] as! String
    let framePath = pigeonVar_list[1] as! String
    let durationMs = pigeonVar_list[2] as! Int64
    let music: NativeAudioTrack? = nilOrValue(pigeonVar_list[3])
    let output = pigeonVar_list[4] as! NativeOutput

    return StillVideoExportRequest(
      jobId: jobId,
      framePath: framePath,
      durationMs: durationMs,
      music: music,
      output: output
    )
  }
  func toList() -> [Any?] {
    return [
      jobId,
      framePath,
      durationMs,
      music,
      output,
    ]
  }
  static func == (lhs: StillVideoExportRequest, rhs: StillVideoExportRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return StoryNativeApiPigeonInternal.deepEquals(lhs.jobId, rhs.jobId) && StoryNativeApiPigeonInternal.deepEquals(lhs.framePath, rhs.framePath) && StoryNativeApiPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && StoryNativeApiPigeonInternal.deepEquals(lhs.music, rhs.music) && StoryNativeApiPigeonInternal.deepEquals(lhs.output, rhs.output)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StillVideoExportRequest")
    StoryNativeApiPigeonInternal.deepHash(value: jobId, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: framePath, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: music, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: output, hasher: &hasher)
  }

  public var description: String {
    return "StillVideoExportRequest(jobId: \(String(describing: jobId)), framePath: \(String(describing: framePath)), durationMs: \(String(describing: durationMs)), music: \(String(describing: music)), output: \(String(describing: output)))"
  }
}

/// JPEG encoding of raw pixels.
///
/// Generated class from Pigeon that represents data sent in messages.
struct JpegEncodeRequest: Hashable, CustomStringConvertible {
  /// Straight (non-premultiplied) RGBA8888, row-major, width*height*4 bytes.
  var rgba: FlutterStandardTypedData
  var width: Int64
  var height: Int64
  /// 1–100.
  var quality: Int64
  var outputPath: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> JpegEncodeRequest? {
    let rgba = pigeonVar_list[0] as! FlutterStandardTypedData
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let quality = pigeonVar_list[3] as! Int64
    let outputPath = pigeonVar_list[4] as! String

    return JpegEncodeRequest(
      rgba: rgba,
      width: width,
      height: height,
      quality: quality,
      outputPath: outputPath
    )
  }
  func toList() -> [Any?] {
    return [
      rgba,
      width,
      height,
      quality,
      outputPath,
    ]
  }
  static func == (lhs: JpegEncodeRequest, rhs: JpegEncodeRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return StoryNativeApiPigeonInternal.deepEquals(lhs.rgba, rhs.rgba) && StoryNativeApiPigeonInternal.deepEquals(lhs.width, rhs.width) && StoryNativeApiPigeonInternal.deepEquals(lhs.height, rhs.height) && StoryNativeApiPigeonInternal.deepEquals(lhs.quality, rhs.quality) && StoryNativeApiPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("JpegEncodeRequest")
    StoryNativeApiPigeonInternal.deepHash(value: rgba, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: quality, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
  }

  public var description: String {
    return "JpegEncodeRequest(rgba: \(String(describing: rgba)), width: \(String(describing: width)), height: \(String(describing: height)), quality: \(String(describing: quality)), outputPath: \(String(describing: outputPath)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeExportResult: Hashable, CustomStringConvertible {
  var path: String
  var width: Int64
  var height: Int64
  var fileSizeBytes: Int64
  var durationMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeExportResult? {
    let path = pigeonVar_list[0] as! String
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let fileSizeBytes = pigeonVar_list[3] as! Int64
    let durationMs: Int64? = nilOrValue(pigeonVar_list[4])

    return NativeExportResult(
      path: path,
      width: width,
      height: height,
      fileSizeBytes: fileSizeBytes,
      durationMs: durationMs
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      width,
      height,
      fileSizeBytes,
      durationMs,
    ]
  }
  static func == (lhs: NativeExportResult, rhs: NativeExportResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return StoryNativeApiPigeonInternal.deepEquals(lhs.path, rhs.path) && StoryNativeApiPigeonInternal.deepEquals(lhs.width, rhs.width) && StoryNativeApiPigeonInternal.deepEquals(lhs.height, rhs.height) && StoryNativeApiPigeonInternal.deepEquals(lhs.fileSizeBytes, rhs.fileSizeBytes) && StoryNativeApiPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeExportResult")
    StoryNativeApiPigeonInternal.deepHash(value: path, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: fileSizeBytes, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
  }

  public var description: String {
    return "NativeExportResult(path: \(String(describing: path)), width: \(String(describing: width)), height: \(String(describing: height)), fileSizeBytes: \(String(describing: fileSizeBytes)), durationMs: \(String(describing: durationMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMediaProbe: Hashable, CustomStringConvertible {
  /// Display size (rotation / EXIF orientation applied).
  var width: Int64
  var height: Int64
  var fileSizeBytes: Int64
  var rotationDegrees: Int64
  var hasVideo: Bool
  var hasAudio: Bool
  var durationMs: Int64? = nil
  var videoCodec: String? = nil
  var audioCodec: String? = nil
  var frameRate: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMediaProbe? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64
    let fileSizeBytes = pigeonVar_list[2] as! Int64
    let rotationDegrees = pigeonVar_list[3] as! Int64
    let hasVideo = pigeonVar_list[4] as! Bool
    let hasAudio = pigeonVar_list[5] as! Bool
    let durationMs: Int64? = nilOrValue(pigeonVar_list[6])
    let videoCodec: String? = nilOrValue(pigeonVar_list[7])
    let audioCodec: String? = nilOrValue(pigeonVar_list[8])
    let frameRate: Double? = nilOrValue(pigeonVar_list[9])

    return NativeMediaProbe(
      width: width,
      height: height,
      fileSizeBytes: fileSizeBytes,
      rotationDegrees: rotationDegrees,
      hasVideo: hasVideo,
      hasAudio: hasAudio,
      durationMs: durationMs,
      videoCodec: videoCodec,
      audioCodec: audioCodec,
      frameRate: frameRate
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      fileSizeBytes,
      rotationDegrees,
      hasVideo,
      hasAudio,
      durationMs,
      videoCodec,
      audioCodec,
      frameRate,
    ]
  }
  static func == (lhs: NativeMediaProbe, rhs: NativeMediaProbe) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return StoryNativeApiPigeonInternal.deepEquals(lhs.width, rhs.width) && StoryNativeApiPigeonInternal.deepEquals(lhs.height, rhs.height) && StoryNativeApiPigeonInternal.deepEquals(lhs.fileSizeBytes, rhs.fileSizeBytes) && StoryNativeApiPigeonInternal.deepEquals(lhs.rotationDegrees, rhs.rotationDegrees) && StoryNativeApiPigeonInternal.deepEquals(lhs.hasVideo, rhs.hasVideo) && StoryNativeApiPigeonInternal.deepEquals(lhs.hasAudio, rhs.hasAudio) && StoryNativeApiPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && StoryNativeApiPigeonInternal.deepEquals(lhs.videoCodec, rhs.videoCodec) && StoryNativeApiPigeonInternal.deepEquals(lhs.audioCodec, rhs.audioCodec) && StoryNativeApiPigeonInternal.deepEquals(lhs.frameRate, rhs.frameRate)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeMediaProbe")
    StoryNativeApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: fileSizeBytes, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: rotationDegrees, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: hasVideo, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: hasAudio, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: videoCodec, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: audioCodec, hasher: &hasher)
    StoryNativeApiPigeonInternal.deepHash(value: frameRate, hasher: &hasher)
  }

  public var description: String {
    return "NativeMediaProbe(width: \(String(describing: width)), height: \(String(describing: height)), fileSizeBytes: \(String(describing: fileSizeBytes)), rotationDegrees: \(String(describing: rotationDegrees)), hasVideo: \(String(describing: hasVideo)), hasAudio: \(String(describing: hasAudio)), durationMs: \(String(describing: durationMs)), videoCodec: \(String(describing: videoCodec)), audioCodec: \(String(describing: audioCodec)), frameRate: \(String(describing: frameRate)))"
  }
}

private class StoryNativeApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeRect.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeAudioTrack.fromList(self.readValue() as! [Any?])
    case 131:
      return NativeOutput.fromList(self.readValue() as! [Any?])
    case 132:
      return VideoExportRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return StillVideoExportRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return JpegEncodeRequest.fromList(self.readValue() as! [Any?])
    case 135:
      return NativeExportResult.fromList(self.readValue() as! [Any?])
    case 136:
      return NativeMediaProbe.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class StoryNativeApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeRect {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAudioTrack {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativeOutput {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? VideoExportRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? StillVideoExportRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? JpegEncodeRequest {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? NativeExportResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMediaProbe {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class StoryNativeApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return StoryNativeApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return StoryNativeApiPigeonCodecWriter(data: data)
  }
}

class StoryNativeApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = StoryNativeApiPigeonCodec(readerWriter: StoryNativeApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol StoryNativeApi {
  func exportVideo(request: VideoExportRequest) async throws -> NativeExportResult
  func exportStillVideo(request: StillVideoExportRequest) async throws -> NativeExportResult
  func encodeJpeg(request: JpegEncodeRequest) async throws -> NativeExportResult
  /// Cancels a running export; its call fails with code 'cancelled' and the
  /// partial output is deleted. No-op for unknown ids.
  func cancelExport(jobId: String) throws
  /// Images (JPEG, PNG, HEIC, WebP) and videos.
  func probe(path: String) async throws -> NativeMediaProbe
  /// Peak levels 0–1 in [buckets] even slices of the whole file's audio.
  func waveform(path: String, buckets: Int64) async throws -> [Double]
  /// JPEG frames at [timesMs], at most [maxWidth] wide, written into
  /// [outputDirectory]; returns paths in the same order.
  func thumbnails(path: String, timesMs: [Int64], maxWidth: Int64, outputDirectory: String) async throws -> [String]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class StoryNativeApiSetup {
  static var codec: FlutterStandardMessageCodec { StoryNativeApiPigeonCodec.shared }
  /// Sets up an instance of `StoryNativeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: StoryNativeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let exportVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.exportVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! VideoExportRequest
        Task { @MainActor in
          do {
            let result = try await api.exportVideo(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      exportVideoChannel.setMessageHandler(nil)
    }
    let exportStillVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.exportStillVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportStillVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! StillVideoExportRequest
        Task { @MainActor in
          do {
            let result = try await api.exportStillVideo(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      exportStillVideoChannel.setMessageHandler(nil)
    }
    let encodeJpegChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.encodeJpeg\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      encodeJpegChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! JpegEncodeRequest
        Task { @MainActor in
          do {
            let result = try await api.encodeJpeg(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      encodeJpegChannel.setMessageHandler(nil)
    }
    /// Cancels a running export; its call fails with code 'cancelled' and the
    /// partial output is deleted. No-op for unknown ids.
    let cancelExportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.cancelExport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelExportChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jobIdArg = args[0] as! String
        do {
          try api.cancelExport(jobId: jobIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelExportChannel.setMessageHandler(nil)
    }
    /// Images (JPEG, PNG, HEIC, WebP) and videos.
    let probeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.probe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      probeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.probe(path: pathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      probeChannel.setMessageHandler(nil)
    }
    /// Peak levels 0–1 in [buckets] even slices of the whole file's audio.
    let waveformChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.waveform\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      waveformChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let bucketsArg = args[1] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.waveform(path: pathArg, buckets: bucketsArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      waveformChannel.setMessageHandler(nil)
    }
    /// JPEG frames at [timesMs], at most [maxWidth] wide, written into
    /// [outputDirectory]; returns paths in the same order.
    let thumbnailsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.thumbnails\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      thumbnailsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let timesMsArg = args[1] as! [Int64]
        let maxWidthArg = args[2] as! Int64
        let outputDirectoryArg = args[3] as! String
        Task { @MainActor in
          do {
            let result = try await api.thumbnails(path: pathArg, timesMs: timesMsArg, maxWidth: maxWidthArg, outputDirectory: outputDirectoryArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      thumbnailsChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol StoryNativeEventsProtocol {
  /// Progress 0–1 of a running export.
  @MainActor func onExportProgress(jobId jobIdArg: String, progress progressArg: Double) async throws
}
class StoryNativeEvents: StoryNativeEventsProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: StoryNativeApiPigeonCodec {
    return StoryNativeApiPigeonCodec.shared
  }
  /// Progress 0–1 of a running export.
  @MainActor func onExportProgress(jobId jobIdArg: String, progress progressArg: Double) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.story_creator_kit.StoryNativeEvents.onExportProgress\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([jobIdArg, progressArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
