import 'package:flutter/painting.dart';
import 'package:story_creator_kit/story_creator_kit.dart';

import 'sample_music_provider.dart';

/// Host-supplied fonts, bundled in `example/assets/fonts` (SIL OFL).
const sampleFonts = [
  StoryFont(id: 'inter', label: 'Classic', family: 'Inter'),
  StoryFont(id: 'playfair', label: 'Serif', family: 'PlayfairDisplay'),
  StoryFont(id: 'pacifico', label: 'Script', family: 'Pacifico', height: 1.4),
  StoryFont(
    id: 'spacemono',
    label: 'Typewriter',
    family: 'SpaceMono',
    uppercase: true,
  ),
];

const _stickerNames = [
  'star',
  'heart',
  'sun',
  'wow',
  'lightning',
  'crown',
  'sparkle',
  'flame',
];

/// Host-supplied stickers, generated by `tool/generate_sample_assets.dart`.
final sampleStickers = [
  for (final name in _stickerNames)
    StorySticker(
      id: name,
      label: name,
      image: AssetImage('assets/stickers/$name.png'),
    ),
];

/// Example settings the home page can change.
class ExampleSettings {
  GalleryMode galleryMode = GalleryMode.inApp;
  int maxVideoSeconds = 60;
  bool showPreview = true;
  SaveToGalleryMode saveMode = SaveToGalleryMode.button;
  bool music = true;
  bool customStrings = false;

  StoryCreatorConfig toConfig({
    required SampleMusicProvider musicProvider,
    required StoryEventCallback onEvent,
  }) => StoryCreatorConfig(
    capture: CaptureOptions(galleryMode: galleryMode),
    constraints: MediaConstraints(
      maxVideoDuration: Duration(seconds: maxVideoSeconds),
    ),
    editor: EditorOptions(fonts: sampleFonts, stickers: sampleStickers),
    output: OutputOptions(showPreview: showPreview, saveToGallery: saveMode),
    musicProvider: music ? musicProvider : null,
    strings: customStrings
        ? const StoryCreatorStrings(
            editor: EditorStrings(export: 'Post', text: 'Aa'),
            export: ExportStrings(useStory: 'Post it'),
          )
        : const StoryCreatorStrings(),
    onEvent: onEvent,
  );
}
