// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.mabrook.story_creator_kit

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object StoryNativeApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * A rectangle in output pixels (origin top-left).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeRect (
  val left: Double,
  val top: Double,
  val width: Double,
  val height: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeRect {
      val left = pigeonVar_list[0] as Double
      val top = pigeonVar_list[1] as Double
      val width = pigeonVar_list[2] as Double
      val height = pigeonVar_list[3] as Double
      return NativeRect(left, top, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      left,
      top,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeRect
    return StoryNativeApiPigeonUtils.deepEquals(this.left, other.left) && StoryNativeApiPigeonUtils.deepEquals(this.top, other.top) && StoryNativeApiPigeonUtils.deepEquals(this.width, other.width) && StoryNativeApiPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.left)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.top)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.width)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "NativeRect(left=$left, top=$top, width=$width, height=$height)"
  }
}

/**
 * An extra audio track mixed into the output.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeAudioTrack (
  /** Local audio file (M4A/AAC, MP3, WAV). */
  val path: String,
  /** Offset into the audio file where playback starts. */
  val startMs: Long,
  /** 0–1. */
  val volume: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAudioTrack {
      val path = pigeonVar_list[0] as String
      val startMs = pigeonVar_list[1] as Long
      val volume = pigeonVar_list[2] as Double
      return NativeAudioTrack(path, startMs, volume)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      startMs,
      volume,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAudioTrack
    return StoryNativeApiPigeonUtils.deepEquals(this.path, other.path) && StoryNativeApiPigeonUtils.deepEquals(this.startMs, other.startMs) && StoryNativeApiPigeonUtils.deepEquals(this.volume, other.volume)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.path)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.startMs)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.volume)
    return result
  }
  override fun toString(): String {
    return "NativeAudioTrack(path=$path, startMs=$startMs, volume=$volume)"
  }
}

/**
 * Common output settings.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeOutput (
  /** Destination .mp4 path; overwritten if it exists. */
  val path: String,
  val width: Long,
  val height: Long,
  val frameRate: Long,
  /** H.264 target bitrate, bits per second. */
  val videoBitrate: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeOutput {
      val path = pigeonVar_list[0] as String
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      val frameRate = pigeonVar_list[3] as Long
      val videoBitrate = pigeonVar_list[4] as Long
      return NativeOutput(path, width, height, frameRate, videoBitrate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      width,
      height,
      frameRate,
      videoBitrate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeOutput
    return StoryNativeApiPigeonUtils.deepEquals(this.path, other.path) && StoryNativeApiPigeonUtils.deepEquals(this.width, other.width) && StoryNativeApiPigeonUtils.deepEquals(this.height, other.height) && StoryNativeApiPigeonUtils.deepEquals(this.frameRate, other.frameRate) && StoryNativeApiPigeonUtils.deepEquals(this.videoBitrate, other.videoBitrate)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.path)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.width)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.height)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.frameRate)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.videoBitrate)
    return result
  }
  override fun toString(): String {
    return "NativeOutput(path=$path, width=$width, height=$height, frameRate=$frameRate, videoBitrate=$videoBitrate)"
  }
}

/**
 * Export of a source video onto the story canvas.
 *
 * Frame composition, bottom to top:
 *   1. transparent/black canvas of output size
 *   2. the source video frame, rotated per its metadata, mirrored when
 *      [mirror], colour-transformed by [colorMatrix], drawn scaled into
 *      [videoRect] (may extend past the canvas; clipped)
 *   3. [overlayPngPath], a full-canvas RGBA PNG drawn at (0,0) at output
 *      size. It already contains the background with a transparent hole
 *      where the video shows, plus drawings and overlays.
 * Audio: the source audio in [trimStartMs, trimEndMs) at [originalVolume]
 * (omitted when 0 or absent), mixed with [music] trimmed to the output
 * length. Output is AAC 44.1 kHz stereo; no audio track when both are
 * absent.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VideoExportRequest (
  val jobId: String,
  val sourcePath: String,
  val trimStartMs: Long,
  val trimEndMs: Long,
  val videoRect: NativeRect,
  val mirror: Boolean,
  /**
   * 20 values, row-major 4×5, offsets in 0–255 (Flutter ColorFilter.matrix
   * semantics). `null` = identity.
   */
  val colorMatrix: List<Double>? = null,
  val overlayPngPath: String? = null,
  val originalVolume: Double,
  val music: NativeAudioTrack? = null,
  val output: NativeOutput
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoExportRequest {
      val jobId = pigeonVar_list[0] as String
      val sourcePath = pigeonVar_list[1] as String
      val trimStartMs = pigeonVar_list[2] as Long
      val trimEndMs = pigeonVar_list[3] as Long
      val videoRect = pigeonVar_list[4] as NativeRect
      val mirror = pigeonVar_list[5] as Boolean
      val colorMatrix = pigeonVar_list[6] as List<Double>?
      val overlayPngPath = pigeonVar_list[7] as String?
      val originalVolume = pigeonVar_list[8] as Double
      val music = pigeonVar_list[9] as NativeAudioTrack?
      val output = pigeonVar_list[10] as NativeOutput
      return VideoExportRequest(jobId, sourcePath, trimStartMs, trimEndMs, videoRect, mirror, colorMatrix, overlayPngPath, originalVolume, music, output)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      jobId,
      sourcePath,
      trimStartMs,
      trimEndMs,
      videoRect,
      mirror,
      colorMatrix,
      overlayPngPath,
      originalVolume,
      music,
      output,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoExportRequest
    return StoryNativeApiPigeonUtils.deepEquals(this.jobId, other.jobId) && StoryNativeApiPigeonUtils.deepEquals(this.sourcePath, other.sourcePath) && StoryNativeApiPigeonUtils.deepEquals(this.trimStartMs, other.trimStartMs) && StoryNativeApiPigeonUtils.deepEquals(this.trimEndMs, other.trimEndMs) && StoryNativeApiPigeonUtils.deepEquals(this.videoRect, other.videoRect) && StoryNativeApiPigeonUtils.deepEquals(this.mirror, other.mirror) && StoryNativeApiPigeonUtils.deepEquals(this.colorMatrix, other.colorMatrix) && StoryNativeApiPigeonUtils.deepEquals(this.overlayPngPath, other.overlayPngPath) && StoryNativeApiPigeonUtils.deepEquals(this.originalVolume, other.originalVolume) && StoryNativeApiPigeonUtils.deepEquals(this.music, other.music) && StoryNativeApiPigeonUtils.deepEquals(this.output, other.output)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.jobId)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.sourcePath)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.trimStartMs)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.trimEndMs)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.videoRect)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.mirror)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.colorMatrix)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.overlayPngPath)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.originalVolume)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.music)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.output)
    return result
  }
  override fun toString(): String {
    return "VideoExportRequest(jobId=$jobId, sourcePath=$sourcePath, trimStartMs=$trimStartMs, trimEndMs=$trimEndMs, videoRect=$videoRect, mirror=$mirror, colorMatrix=$colorMatrix, overlayPngPath=$overlayPngPath, originalVolume=$originalVolume, music=$music, output=$output)"
  }
}

/**
 * A video made from one still frame (photo story with music).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StillVideoExportRequest (
  val jobId: String,
  /** Fully composed frame at output size (PNG or JPEG). */
  val framePath: String,
  val durationMs: Long,
  val music: NativeAudioTrack? = null,
  val output: NativeOutput
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StillVideoExportRequest {
      val jobId = pigeonVar_list[0] as String
      val framePath = pigeonVar_list[1] as String
      val durationMs = pigeonVar_list[2] as Long
      val music = pigeonVar_list[3] as NativeAudioTrack?
      val output = pigeonVar_list[4] as NativeOutput
      return StillVideoExportRequest(jobId, framePath, durationMs, music, output)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      jobId,
      framePath,
      durationMs,
      music,
      output,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StillVideoExportRequest
    return StoryNativeApiPigeonUtils.deepEquals(this.jobId, other.jobId) && StoryNativeApiPigeonUtils.deepEquals(this.framePath, other.framePath) && StoryNativeApiPigeonUtils.deepEquals(this.durationMs, other.durationMs) && StoryNativeApiPigeonUtils.deepEquals(this.music, other.music) && StoryNativeApiPigeonUtils.deepEquals(this.output, other.output)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.jobId)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.framePath)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.music)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.output)
    return result
  }
  override fun toString(): String {
    return "StillVideoExportRequest(jobId=$jobId, framePath=$framePath, durationMs=$durationMs, music=$music, output=$output)"
  }
}

/**
 * JPEG encoding of raw pixels.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class JpegEncodeRequest (
  /** Straight (non-premultiplied) RGBA8888, row-major, width*height*4 bytes. */
  val rgba: ByteArray,
  val width: Long,
  val height: Long,
  /** 1–100. */
  val quality: Long,
  val outputPath: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): JpegEncodeRequest {
      val rgba = pigeonVar_list[0] as ByteArray
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      val quality = pigeonVar_list[3] as Long
      val outputPath = pigeonVar_list[4] as String
      return JpegEncodeRequest(rgba, width, height, quality, outputPath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rgba,
      width,
      height,
      quality,
      outputPath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as JpegEncodeRequest
    return StoryNativeApiPigeonUtils.deepEquals(this.rgba, other.rgba) && StoryNativeApiPigeonUtils.deepEquals(this.width, other.width) && StoryNativeApiPigeonUtils.deepEquals(this.height, other.height) && StoryNativeApiPigeonUtils.deepEquals(this.quality, other.quality) && StoryNativeApiPigeonUtils.deepEquals(this.outputPath, other.outputPath)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.rgba)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.width)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.height)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.quality)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.outputPath)
    return result
  }
  override fun toString(): String {
    return "JpegEncodeRequest(rgba=${rgba.contentToString()}, width=$width, height=$height, quality=$quality, outputPath=$outputPath)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeExportResult (
  val path: String,
  val width: Long,
  val height: Long,
  val fileSizeBytes: Long,
  val durationMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeExportResult {
      val path = pigeonVar_list[0] as String
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      val fileSizeBytes = pigeonVar_list[3] as Long
      val durationMs = pigeonVar_list[4] as Long?
      return NativeExportResult(path, width, height, fileSizeBytes, durationMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      width,
      height,
      fileSizeBytes,
      durationMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeExportResult
    return StoryNativeApiPigeonUtils.deepEquals(this.path, other.path) && StoryNativeApiPigeonUtils.deepEquals(this.width, other.width) && StoryNativeApiPigeonUtils.deepEquals(this.height, other.height) && StoryNativeApiPigeonUtils.deepEquals(this.fileSizeBytes, other.fileSizeBytes) && StoryNativeApiPigeonUtils.deepEquals(this.durationMs, other.durationMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.path)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.width)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.height)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.fileSizeBytes)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.durationMs)
    return result
  }
  override fun toString(): String {
    return "NativeExportResult(path=$path, width=$width, height=$height, fileSizeBytes=$fileSizeBytes, durationMs=$durationMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeMediaProbe (
  /** Display size (rotation / EXIF orientation applied). */
  val width: Long,
  val height: Long,
  val fileSizeBytes: Long,
  val rotationDegrees: Long,
  val hasVideo: Boolean,
  val hasAudio: Boolean,
  val durationMs: Long? = null,
  val videoCodec: String? = null,
  val audioCodec: String? = null,
  val frameRate: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeMediaProbe {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      val fileSizeBytes = pigeonVar_list[2] as Long
      val rotationDegrees = pigeonVar_list[3] as Long
      val hasVideo = pigeonVar_list[4] as Boolean
      val hasAudio = pigeonVar_list[5] as Boolean
      val durationMs = pigeonVar_list[6] as Long?
      val videoCodec = pigeonVar_list[7] as String?
      val audioCodec = pigeonVar_list[8] as String?
      val frameRate = pigeonVar_list[9] as Double?
      return NativeMediaProbe(width, height, fileSizeBytes, rotationDegrees, hasVideo, hasAudio, durationMs, videoCodec, audioCodec, frameRate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
      fileSizeBytes,
      rotationDegrees,
      hasVideo,
      hasAudio,
      durationMs,
      videoCodec,
      audioCodec,
      frameRate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeMediaProbe
    return StoryNativeApiPigeonUtils.deepEquals(this.width, other.width) && StoryNativeApiPigeonUtils.deepEquals(this.height, other.height) && StoryNativeApiPigeonUtils.deepEquals(this.fileSizeBytes, other.fileSizeBytes) && StoryNativeApiPigeonUtils.deepEquals(this.rotationDegrees, other.rotationDegrees) && StoryNativeApiPigeonUtils.deepEquals(this.hasVideo, other.hasVideo) && StoryNativeApiPigeonUtils.deepEquals(this.hasAudio, other.hasAudio) && StoryNativeApiPigeonUtils.deepEquals(this.durationMs, other.durationMs) && StoryNativeApiPigeonUtils.deepEquals(this.videoCodec, other.videoCodec) && StoryNativeApiPigeonUtils.deepEquals(this.audioCodec, other.audioCodec) && StoryNativeApiPigeonUtils.deepEquals(this.frameRate, other.frameRate)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.width)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.height)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.fileSizeBytes)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.rotationDegrees)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.hasVideo)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.hasAudio)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.videoCodec)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.audioCodec)
    result = 31 * result + StoryNativeApiPigeonUtils.deepHash(this.frameRate)
    return result
  }
  override fun toString(): String {
    return "NativeMediaProbe(width=$width, height=$height, fileSizeBytes=$fileSizeBytes, rotationDegrees=$rotationDegrees, hasVideo=$hasVideo, hasAudio=$hasAudio, durationMs=$durationMs, videoCodec=$videoCodec, audioCodec=$audioCodec, frameRate=$frameRate)"
  }
}
private open class StoryNativeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeRect.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAudioTrack.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeOutput.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoExportRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StillVideoExportRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          JpegEncodeRequest.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeExportResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeMediaProbe.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeRect -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeAudioTrack -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeOutput -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is VideoExportRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is StillVideoExportRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is JpegEncodeRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is NativeExportResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is NativeMediaProbe -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface StoryNativeApi {
  suspend fun exportVideo(request: VideoExportRequest): NativeExportResult
  suspend fun exportStillVideo(request: StillVideoExportRequest): NativeExportResult
  suspend fun encodeJpeg(request: JpegEncodeRequest): NativeExportResult
  /**
   * Cancels a running export; its call fails with code 'cancelled' and the
   * partial output is deleted. No-op for unknown ids.
   */
  fun cancelExport(jobId: String)
  /** Images (JPEG, PNG, HEIC, WebP) and videos. */
  suspend fun probe(path: String): NativeMediaProbe
  /** Peak levels 0–1 in [buckets] even slices of the whole file's audio. */
  suspend fun waveform(path: String, buckets: Long): List<Double>
  /**
   * JPEG frames at [timesMs], at most [maxWidth] wide, written into
   * [outputDirectory]; returns paths in the same order.
   */
  suspend fun thumbnails(path: String, timesMs: List<Long>, maxWidth: Long, outputDirectory: String): List<String>

  companion object {
    /** The codec used by StoryNativeApi. */
    val codec: MessageCodec<Any?> by lazy {
      StoryNativeApiPigeonCodec()
    }
    /** Sets up an instance of `StoryNativeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: StoryNativeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.exportVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VideoExportRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.exportVideo(requestArg))
              } catch (exception: Throwable) {
                StoryNativeApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.exportStillVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as StillVideoExportRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.exportStillVideo(requestArg))
              } catch (exception: Throwable) {
                StoryNativeApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.encodeJpeg$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as JpegEncodeRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.encodeJpeg(requestArg))
              } catch (exception: Throwable) {
                StoryNativeApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.cancelExport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jobIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancelExport(jobIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              StoryNativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.probe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.probe(pathArg))
              } catch (exception: Throwable) {
                StoryNativeApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.waveform$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val bucketsArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.waveform(pathArg, bucketsArg))
              } catch (exception: Throwable) {
                StoryNativeApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.story_creator_kit.StoryNativeApi.thumbnails$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val timesMsArg = args[1] as List<Long>
            val maxWidthArg = args[2] as Long
            val outputDirectoryArg = args[3] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.thumbnails(pathArg, timesMsArg, maxWidthArg, outputDirectoryArg))
              } catch (exception: Throwable) {
                StoryNativeApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class StoryNativeEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by StoryNativeEvents. */
    val codec: MessageCodec<Any?> by lazy {
      StoryNativeApiPigeonCodec()
    }
  }
  /** Progress 0–1 of a running export. */
  suspend fun onExportProgress(jobIdArg: String, progressArg: Double)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.story_creator_kit.StoryNativeEvents.onExportProgress$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(jobIdArg, progressArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(StoryNativeApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
